[workspace]
resolver = "2"
members = [
  "axum-tracing-opentelemetry",
  "examples/*",
  "fake-opentelemetry-collector",
  "init-tracing-opentelemetry",
  "testing-tracing-opentelemetry",
  # "tonic-tracing-opentelemetry",
  "tracing-opentelemetry-instrumentation-sdk",
]

exclude = ["examples/grpc", "target", "tonic-tracing-opentelemetry"]

[workspace.package]
edition = "2021"
version = "0.16.1"
authors = ["David Bernard"]
license = "CC0-1.0"
repository = "https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk"
rust-version = "1.70"

[workspace.dependencies]
http = "^1"
opentelemetry = { version = "0.21", features = [
  "trace",
], default-features = false }
opentelemetry-otlp = { version = "0.14", default-features = false }
opentelemetry-proto = { version = "0.4", default-features = false }
opentelemetry_sdk = { version = "0.21", default-features = false, features = [
  "rt-tokio",
] }
tracing = "0.1"
tracing-opentelemetry = "0.22"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[workspace.metadata.release]
pre-release-commit-message = "🚀 (cargo-release) version {{version}}"
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"
tag-message = "🔖 {{version}}"
