[package]
name = "axum-tracing-opentelemetry"
description = "Middlewares and tools to integrate axum + tracing + opentelemetry"
version = "0.10.0"
edition = "2021"
readme = "README.md"
license = "CC0-1.0"
keywords = ["axum", "tracing", "opentelemetry"]
categories = ["web-programming"]
repository = "https://github.com/davidB/axum-tracing-opentelemetry"
homepage = "https://github.com/davidB/axum-tracing-opentelemetry"

[dependencies]
axum = "0.6"
# axum-core = "0.3"
futures = "0.3"
http = "0.2"
opentelemetry = { version = "0.20", features = ["rt-tokio"] }
opentelemetry-aws = { version = "0.8", optional = true }
opentelemetry-jaeger = { version = "0.19", features = [
  "rt-tokio",
], optional = true }
opentelemetry-semantic-conventions = { version = "0.12", optional = true }
opentelemetry-otlp = { version = "0.13", optional = true, features = [
  "http-proto",
] }
opentelemetry-zipkin = { version = "0.18", features = [], optional = true }
tower = "0.4"
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-opentelemetry = "0.20.0"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "ansi",
  "env-filter",
  "fmt",
  "json",
], optional = true }

[dev-dependencies]
assert2 = "0.3"
assert-json-diff = "2.0"
hyper = "0.14"
opentelemetry-otlp = { version = "0.13", features = [
  "http-proto",
  "reqwest-client",
  "reqwest-rustls",
] }
rstest = "0.16"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.33", features = ["full"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
  "json",
] }

[features]
jaeger = ["dep:opentelemetry-jaeger", "tracer"]
otlp = ["dep:opentelemetry-otlp", "tracer"]
tracer = ["dep:opentelemetry-semantic-conventions"]
xray = ["dep:opentelemetry-aws"]
zipkin = ["dep:opentelemetry-zipkin"]
tracing_subscriber_ext = ["dep:tracing-subscriber"]
